### ISSUE TITLE
macos本地部署上传应用报错

### ISSUE THREAD

**Issue by Cabriter** [tryzealot/zealot-docker#11]
报错内容:非常抱歉，服务当前遇到一些技术问题造成访问异常。

按照快速上手中用默认配置构建
docker version:20.10.8
docker-composr version:v2.0.0-rc.1

**Comment by icyleaf** [comment]
部署脚本执行之后会生成一份日志文件，文件名是 `zealot_install_log_*.txt` 的格式，能把内容贴一下么

**Comment by Cabriter** [comment]
好的，稍后贴上去，我后来去示例的部署站点去测试发现示例的站点也是会上传包错误。

**Comment by Cabriter** [comment]
[zealot_install_log-2021-08-23_11-13-40.txt](https://github.com/tryzealot/zealot-docker/files/7029306/zealot_install_log-2021-08-23_11-13-40.txt)
构建日志

**Comment by icyleaf** [comment]
你的域名没有正常配置呀，`ZEALOT_DOMAIN=Domain`

**Comment by icyleaf** [comment]
> 好的，稍后贴上去，我后来去示例的部署站点去测试发现示例的站点也是会上传包错误。

https://tryzealot.herokuapp.com/ 我测试了 apk 和 ipa 都是正常的

**Comment by Cabriter** [comment]
这个域名的修改,直接config.env后重新启动docker-composr就可以了吗?

**Comment by icyleaf** [comment]
`config.env` 这是模板，脚本会复制并生成一个新的叫 `.env` 的文件修改他在重启，是不是你对 docker 使用上还不是特别熟悉？

**Comment by Cabriter** [comment]
我做了这个操作,主页打不开了.😂
[zealot_install_log-2021-08-23_15-04-15.txt](https://github.com/tryzealot/zealot-docker/files/7029816/zealot_install_log-2021-08-23_15-04-15.txt)

**Comment by Cabriter** [comment]
> > 好的，稍后贴上去，我后来去示例的部署站点去测试发现示例的站点也是会上传包错误。
> 
> https://tryzealot.herokuapp.com/ 我测试了 apk 和 ipa 都是正常的

![image](https://user-images.githubusercontent.com/12536807/130412094-3d72b90a-b3c2-491f-80fa-efce3e9559a2.png)
我在官方测试的站点测试上传是这样的.

**Comment by Cabriter** [comment]
> `config.env` 这是模板，脚本会复制并生成一个新的叫 `.env` 的文件修改他在重启，是不是你对 docker 使用上还不是特别熟悉？

这个问题,我在执行deploy脚本后让我输入域名,输入了,在执行完后并没有生成新的.env的配置文件,我尝试了多次.

![image](https://user-images.githubusercontent.com/12536807/130413483-461fb737-bdc4-4713-ba6b-bd203497dd49.png)

**Comment by Cabriter** [comment]
> > `config.env` 这是模板，脚本会复制并生成一个新的叫 `.env` 的文件修改他在重启，是不是你对 docker 使用上还不是特别熟悉？
> 
> 这个问题,我在执行deploy脚本后让我输入域名,输入了,在执行完后并没有生成新的.env的配置文件,我尝试了多次.
> 
> ![image](https://user-images.githubusercontent.com/12536807/130413483-461fb737-bdc4-4713-ba6b-bd203497dd49.png)

这个问题是我的问题,我理解成了会生成一个叫xxxx.env的文件,这个文件是隐藏的文件,所以没有看到.

现在确认了一开始的问题应该不是域名引起的,因为我查看了我的.env文件,是有域名的.
![image](https://user-images.githubusercontent.com/12536807/130414180-e092db6f-959f-4d24-95f5-795a652901e4.png)

**Comment by icyleaf** [comment]
看到报错了，有些数据解析异常了，还是说 apk 做了加固？

方便把 apk 文件用临时网盘 https://cowtransfer.com/ 发一份分析下结构吗，感谢

**Comment by Cabriter** [comment]
> 看到报错了，有些数据解析异常了，还是说 apk 做了加固？
> 
> 方便把 apk 文件用临时网盘 https://cowtransfer.com/ 发一份分析下结构吗，感谢

可以

你有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/a5823daa680941 或进入 cowtransfer.com 获取，在首页输入取件码：623777（24 小时内有效）

**Comment by icyleaf** [comment]
初步看了下 apk 是有做安全加固吧， AndroidManifest.xml 文件读不到任何信息

**Comment by icyleaf** [comment]
初步看了下 apk 是有做安全加固吧， AndroidManifest.xml 文件读不到任何信息

**Comment by icyleaf** [comment]
如果有需要强上传加固的应用需求的话也可以提出来 :P

**Comment by Cabriter** [comment]
暂时不需要,内部测试用一般不需要加固.
当时碰到这个问题主要是随便拿了个包上传用来测试的.

**Comment by icyleaf** [comment]
发现谨慎的验证并不是加固了而是 ruby 依赖的一个较老的 apk 解析器现在已经更新为较新的版本，你提供的那个 apk 文件已经支持解析 😄 ，后续可以通过 `nightly` tag 可以尝试下

相关 https://github.com/tryzealot/zealot/commit/5e8e3faffdd2fb518a80652cea1c312c82898a29
