### ISSUE TITLE
API（/api/apps/latest）查询结果有问题

### ISSUE THREAD

**Issue by FE-wangjb** [tryzealot/zealot-docker#15]
API: /api/apps/latest
版本：ghcr.io/tryzealot/zealot:nightly
无论上传几个版本，API查询出的都是第一个上传版本
查询结果：
![图片](https://github.com/tryzealot/zealot-docker/assets/73329369/9c6c1cd0-d105-44a0-9b36-e4ef730ff0e7)
版本列表：
![图片](https://github.com/tryzealot/zealot-docker/assets/73329369/3183fff4-9aa4-4dfa-8656-12ec724f4a15)

**Comment by icyleaf** [comment]
感谢反馈，问题已确认，这类问题后续可以在[zealot](https://github.com/tryzealot/zealot/issues/new)项目提。

**Comment by FE-wangjb** [comment]
> 感谢反馈，问题已确认，这类问题后续可以在[zealot](https://github.com/tryzealot/zealot/issues/new)项目提。

好的
