### ISSUE TITLE
想去掉注册邮箱验证功能要怎么做

### ISSUE THREAD

**Issue by yuweixx** [tryzealot/zealot-docker#4]
我现在的部署环境无法访问邮件服务，所以想去掉注册时的邮箱验证，以保证能正常使用zealot。请问要改动哪里比较方便？

**Comment by icyleaf** [comment]
管理员可以在用户管理拿到激活的链接，可以把链接发给对应的人，看下图：

<img width="1402" alt="user-active-email" src="https://user-images.githubusercontent.com/17814/101468486-70704300-397e-11eb-9ca7-444867e88dc1.png">

**Comment by yuweixx** [comment]
已解决，谢谢

**Comment by icyleaf** [comment]
有其他问题欢迎再提
