### ISSUE TITLE
非常抱歉，服务当前遇到一些技术问题造成访问异常。

### ISSUE THREAD

**Issue by LoadingMx** [tryzealot/zealot-docker#6]
部署方式1：docker 纯zealot模式，配合 Nginx ，平台：云服务器
部署方法2：自签名 SSL 证书，修改hosts，平台：MacOS（本地）
域名访问（500）页面显示“非常抱歉，服务当前遇到一些技术问题造成访问异常。”

怎样排查问题

**Comment by icyleaf** [comment]
如果使用 docker-compose 部署的可以通过提供日志，方法如下：

```bash
docker-compose logs -f zealot
```

**Comment by mengx16** [comment]
➜  zealot-docker git:(master) ✗ docker-compose logs -f zealot
Attaching to zealot-zealot
zealot-zealot | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
zealot-zealot | [s6-init] ensuring user provided files have correct perms...exited 0.
zealot-zealot | [fix-attrs.d] applying ownership & permissions fixes...
zealot-zealot | [fix-attrs.d] 11-crontab-dir: applying...
zealot-zealot | [fix-attrs.d] 11-crontab-dir: exited 0.
zealot-zealot | [fix-attrs.d] done.
zealot-zealot | [cont-init.d] executing container initialization scripts...
zealot-zealot | [cont-init.d] 01-set-timezone: executing...
zealot-zealot | [cont-init.d] 01-set-timezone: exited 0.
zealot-zealot | [cont-init.d] 11-set-crontab: executing...
zealot-zealot | [cont-init.d] 11-set-crontab: exited 0.
zealot-zealot | [cont-init.d] 12-logrotate: executing...
zealot-zealot | exec: fatal: unable to exec bash: No such file or directory
zealot-zealot | [cont-init.d] 12-logrotate: exited 127.
zealot-zealot | [cont-init.d] 20-init-zealot: executing...
zealot-zealot | Zealot updating public ...
zealot-zealot | [cont-init.d] 20-init-zealot: exited 0.
zealot-zealot | [cont-init.d] 25-upgrade-zealot: executing...
zealot-zealot | Zealot upgrade database ...
zealot-zealot | [cont-init.d] 25-upgrade-zealot: exited 0.
zealot-zealot | [cont-init.d] done.
zealot-zealot | [services.d] starting services
zealot-zealot | ========================================
zealot-zealot |   Zealot had change run-way inside, if fail to run make sure
zealot-zealot |   to upgrade the zealot-docker repospitory and re-generate the docker-compose.yml!
zealot-zealot | ========================================
zealot-zealot |
zealot-zealot | Starting Zealot
zealot-zealot | Starting Zealot Worker
zealot-zealot | [services.d] done.
zealot-zealot | [350] Puma starting in cluster mode...
zealot-zealot | [350] * Puma version: 5.3.2 (ruby 2.7.4-p191) ("Sweetnighter")
zealot-zealot | [350] *  Min threads: 5
zealot-zealot | [350] *  Max threads: 5
zealot-zealot | [350] *  Environment: production
zealot-zealot | [350] *   Master PID: 350
zealot-zealot | [350] *      Workers: 2
zealot-zealot | [350] *     Restarts: (✔) hot (✖) phased
zealot-zealot | [350] * Preloading application
zealot-zealot | 2021-07-11T06:43:53.838Z pid=349 tid=d8p INFO: Booting Sidekiq 6.2.1 with redis options {:url=>"redis://redis:6379/0"}
zealot-zealot | 2021-07-11T06:43:53.879Z pid=349 tid=d8p INFO: SidekiqScheduler is disabled
zealot-zealot | [350] * Listening on http://0.0.0.0:3000
zealot-zealot | [350] Use Ctrl-C to stop
zealot-zealot | [350] - Worker 0 (PID: 363) booted in 0.0s, phase: 0
zealot-zealot | [350] - Worker 1 (PID: 370) booted in 0.0s, phase: 0
zealot-zealot | 2021-07-11T06:43:55.303Z pid=349 tid=d8p INFO: Booted Rails 6.1.4 application in production environment
zealot-zealot | 2021-07-11T06:43:55.303Z pid=349 tid=d8p INFO: Running in ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
zealot-zealot | 2021-07-11T06:43:55.303Z pid=349 tid=d8p INFO: See LICENSE and the LGPL-3.0 for licensing details.
zealot-zealot | 2021-07-11T06:43:55.303Z pid=349 tid=d8p INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
zealot-zealot | 2021-07-11T06:43:55.306Z pid=349 tid=d8p INFO: Loading Schedule
zealot-zealot | 2021-07-11T06:43:55.306Z pid=349 tid=d8p INFO: Scheduling clean_old_releases {"cron"=>"0 6 * * *", "class"=>"CleanOldReleasesJob", "queue"=>"schedule", "description"=>"Clean old versions on each 6 AM"}
zealot-zealot | 2021-07-11T06:43:55.309Z pid=349 tid=d8p INFO: Schedules Loaded
zealot-zealot | I, [2021-07-11T14:44:17.733192 #370]  INFO -- : [3e20e7c0-1809-4440-93f1-389440747ebf] Started GET "/" for 172.22.0.1 at 2021-07-11 14:44:17 +0800
zealot-zealot | I, [2021-07-11T14:44:17.739041 #370]  INFO -- : [3e20e7c0-1809-4440-93f1-389440747ebf] Processing by DashboardsController#index as HTML
zealot-zealot | /app/app/controllers/application_controller.rb:30: warning: #<Class:Sentry>#set_user at /usr/local/lib/ruby/2.7.0/forwardable.rb:154 forwarding to private method NilClass#set_user
zealot-zealot | I, [2021-07-11T14:44:17.748833 #370]  INFO -- : [3e20e7c0-1809-4440-93f1-389440747ebf] Completed 500 Internal Server Error in 9ms (Allocations: 1180)
zealot-zealot | F, [2021-07-11T14:44:17.749837 #370] FATAL -- : [3e20e7c0-1809-4440-93f1-389440747ebf]
zealot-zealot | [3e20e7c0-1809-4440-93f1-389440747ebf] NoMethodError (undefined method `set_user' for nil:NilClass):
zealot-zealot | [3e20e7c0-1809-4440-93f1-389440747ebf]
zealot-zealot | [3e20e7c0-1809-4440-93f1-389440747ebf] app/controllers/application_controller.rb:30:in `set_sentry_context'
zealot-zealot | I, [2021-07-11T14:44:18.015774 #370]  INFO -- : [a0946ccc-9e93-4297-a7bd-604024890134] Started GET "/health" for 127.0.0.1 at 2021-07-11 14:44:18 +0800
zealot-zealot | I, [2021-07-11T14:44:18.017276 #370]  INFO -- : [a0946ccc-9e93-4297-a7bd-604024890134] Processing by HealthCheck::HealthCheckController#index as TEXT
zealot-zealot | I, [2021-07-11T14:44:18.057611 #370]  INFO -- : [a0946ccc-9e93-4297-a7bd-604024890134]   Rendered text template (Duration: 0.0ms | Allocations: 3)
zealot-zealot | I, [2021-07-11T14:44:18.057847 #370]  INFO -- : [a0946ccc-9e93-4297-a7bd-604024890134] health_check failed: [redis - ERR Client sent AUTH, but no password is set] ..
zealot-zealot | I, [2021-07-11T14:44:18.058198 #370]  INFO -- : [a0946ccc-9e93-4297-a7bd-604024890134] Completed 500 Internal Server Error in 41ms (Views: 1.2ms | ActiveRecord: 15.2ms | Allocations: 4900)
zealot-zealot | I, [2021-07-11T14:44:48.132504 #363]  INFO -- : [a9ae7514-4ea3-48ef-a8d6-085df15a4f3d] Started GET "/health" for 127.0.0.1 at 2021-07-11 14:44:48 +0800
zealot-zealot | I, [2021-07-11T14:44:48.141483 #363]  INFO -- : [a9ae7514-4ea3-48ef-a8d6-085df15a4f3d] Processing by HealthCheck::HealthCheckController#index as TEXT
zealot-zealot | I, [2021-07-11T14:44:48.181316 #363]  INFO -- : [a9ae7514-4ea3-48ef-a8d6-085df15a4f3d]   Rendered text template (Duration: 0.1ms | Allocations: 3)
zealot-zealot | I, [2021-07-11T14:44:48.181754 #363]  INFO -- : [a9ae7514-4ea3-48ef-a8d6-085df15a4f3d] health_check failed: [redis - ERR Client sent AUTH, but no password is set] ..
zealot-zealot | I, [2021-07-11T14:44:48.182735 #363]  INFO -- : [a9ae7514-4ea3-48ef-a8d6-085df15a4f3d] Completed 500 Internal Server Error in 40ms (Views: 1.5ms | ActiveRecord: 12.9ms | Allocations: 4932)

**Comment by icyleaf** [comment]
已查明问题，等待 https://github.com/tryzealot/zealot/actions/runs/1019666346 这个跑完之后执行下 `docker-compose pull` 在运行就应该没问题了 :D

**Comment by mengx16** [comment]
```
✗ docker-compose logs -f zealot
Attaching to zealot-zealot
zealot-zealot | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
zealot-zealot | [s6-init] ensuring user provided files have correct perms...exited 0.
zealot-zealot | [fix-attrs.d] applying ownership & permissions fixes...
zealot-zealot | [fix-attrs.d] 11-crontab-dir: applying...
zealot-zealot | [fix-attrs.d] 11-crontab-dir: exited 0.
zealot-zealot | [fix-attrs.d] done.
zealot-zealot | [cont-init.d] executing container initialization scripts...
zealot-zealot | [cont-init.d] 01-set-timezone: executing...
zealot-zealot | [cont-init.d] 01-set-timezone: exited 0.
zealot-zealot | [cont-init.d] 11-set-crontab: executing...
zealot-zealot | [cont-init.d] 11-set-crontab: exited 0.
zealot-zealot | [cont-init.d] 12-logrotate: executing...
zealot-zealot | exec: fatal: unable to exec bash: No such file or directory
zealot-zealot | [cont-init.d] 12-logrotate: exited 127.
zealot-zealot | [cont-init.d] 20-init-zealot: executing...
zealot-zealot | Zealot updating public ...
zealot-zealot | [cont-init.d] 20-init-zealot: exited 0.
zealot-zealot | [cont-init.d] 25-upgrade-zealot: executing...
zealot-zealot | Zealot upgrade database ...
zealot-zealot | [cont-init.d] 25-upgrade-zealot: exited 0.
zealot-zealot | [cont-init.d] done.
zealot-zealot | [services.d] starting services
zealot-zealot | Starting Zealot Worker
zealot-zealot | ========================================
zealot-zealot |   Zealot had change run-way inside, if fail to run make sure
zealot-zealot |   to upgrade the zealot-docker repospitory and re-generate the docker-compose.yml!
zealot-zealot | ========================================
zealot-zealot |
zealot-zealot | Starting Zealot
zealot-zealot | [services.d] done.
zealot-zealot | [349] Puma starting in cluster mode...
zealot-zealot | [349] * Puma version: 5.3.2 (ruby 2.7.4-p191) ("Sweetnighter")
zealot-zealot | [349] *  Min threads: 5
zealot-zealot | [349] *  Max threads: 5
zealot-zealot | [349] *  Environment: production
zealot-zealot | [349] *   Master PID: 349
zealot-zealot | [349] *      Workers: 2
zealot-zealot | [349] *     Restarts: (✔) hot (✖) phased
zealot-zealot | [349] * Preloading application
zealot-zealot | 2021-07-11T13:49:03.653Z pid=348 tid=d8o INFO: Booting Sidekiq 6.2.1 with redis options {:url=>"redis://redis:6379/0"}
zealot-zealot | 2021-07-11T13:49:03.696Z pid=348 tid=d8o INFO: SidekiqScheduler is disabled
zealot-zealot | 2021-07-11T13:49:05.159Z pid=348 tid=d8o INFO: Booted Rails 6.1.4 application in production environment
zealot-zealot | 2021-07-11T13:49:05.159Z pid=348 tid=d8o INFO: Running in ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
zealot-zealot | 2021-07-11T13:49:05.159Z pid=348 tid=d8o INFO: See LICENSE and the LGPL-3.0 for licensing details.
zealot-zealot | 2021-07-11T13:49:05.159Z pid=348 tid=d8o INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
zealot-zealot | 2021-07-11T13:49:05.161Z pid=348 tid=d8o INFO: Loading Schedule
zealot-zealot | 2021-07-11T13:49:05.161Z pid=348 tid=d8o INFO: Scheduling clean_old_releases {"cron"=>"0 6 * * *", "class"=>"CleanOldReleasesJob", "queue"=>"schedule", "description"=>"Clean old versions on each 6 AM"}
zealot-zealot | 2021-07-11T13:49:05.164Z pid=348 tid=d8o INFO: Schedules Loaded
zealot-zealot | [349] * Listening on http://0.0.0.0:3000
zealot-zealot | [349] Use Ctrl-C to stop
zealot-zealot | [349] - Worker 0 (PID: 371) booted in 0.0s, phase: 0
zealot-zealot | [349] - Worker 1 (PID: 378) booted in 0.0s, phase: 0
zealot-zealot | I, [2021-07-11T21:49:28.010492 #378]  INFO -- : [1ed44556-0db2-4675-90a5-e2fc904af9b2] Started GET "/health" for 127.0.0.1 at 2021-07-11 21:49:28 +0800
zealot-zealot | I, [2021-07-11T21:49:28.015490 #378]  INFO -- : [1ed44556-0db2-4675-90a5-e2fc904af9b2] Processing by HealthCheck::HealthCheckController#index as TEXT
zealot-zealot | I, [2021-07-11T21:49:28.052099 #378]  INFO -- : [1ed44556-0db2-4675-90a5-e2fc904af9b2]   Rendered text template (Duration: 0.0ms | Allocations: 3)
zealot-zealot | I, [2021-07-11T21:49:28.052384 #378]  INFO -- : [1ed44556-0db2-4675-90a5-e2fc904af9b2] health_check failed: [redis - ERR Client sent AUTH, but no password is set] ..
zealot-zealot | I, [2021-07-11T21:49:28.052819 #378]  INFO -- : [1ed44556-0db2-4675-90a5-e2fc904af9b2] Completed 500 Internal Server Error in 37ms (Views: 1.2ms | ActiveRecord: 10.9ms | Allocations: 4933)
zealot-zealot | I, [2021-07-11T21:49:58.119773 #371]  INFO -- : [862e3039-0587-4895-ab39-16bbbf9a88be] Started GET "/health" for 127.0.0.1 at 2021-07-11 21:49:58 +0800
zealot-zealot | I, [2021-07-11T21:49:58.124067 #371]  INFO -- : [862e3039-0587-4895-ab39-16bbbf9a88be] Processing by HealthCheck::HealthCheckController#index as TEXT
zealot-zealot | I, [2021-07-11T21:49:58.158165 #371]  INFO -- : [862e3039-0587-4895-ab39-16bbbf9a88be]   Rendered text template (Duration: 0.0ms | Allocations: 3)
zealot-zealot | I, [2021-07-11T21:49:58.158360 #371]  INFO -- : [862e3039-0587-4895-ab39-16bbbf9a88be] health_check failed: [redis - ERR Client sent AUTH, but no password is set] ..
zealot-zealot | I, [2021-07-11T21:49:58.158662 #371]  INFO -- : [862e3039-0587-4895-ab39-16bbbf9a88be] Completed 500 Internal Server Error in 34ms (Views: 0.9ms | ActiveRecord: 10.2ms | Allocations: 4933)
zealot-zealot | I, [2021-07-11T21:49:59.650038 #371]  INFO -- : [75575112-72bd-4adb-a818-2b71f080a26f] Started GET "/" for 172.26.0.1 at 2021-07-11 21:49:59 +0800
zealot-zealot | /app/app/controllers/application_controller.rb:30: warning: #<Class:Sentry>#set_extras at /usr/local/lib/ruby/2.7.0/forwardable.rb:154 forwarding to private method NilClass#set_extras
zealot-zealot | I, [2021-07-11T21:49:59.651420 #371]  INFO -- : [75575112-72bd-4adb-a818-2b71f080a26f] Processing by DashboardsController#index as HTML
zealot-zealot | I, [2021-07-11T21:49:59.656396 #371]  INFO -- : [75575112-72bd-4adb-a818-2b71f080a26f] Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.0ms | Allocations: 1189)
zealot-zealot | F, [2021-07-11T21:49:59.657322 #371] FATAL -- : [75575112-72bd-4adb-a818-2b71f080a26f]
zealot-zealot | [75575112-72bd-4adb-a818-2b71f080a26f] NoMethodError (undefined method `set_extras' for nil:NilClass):
zealot-zealot | [75575112-72bd-4adb-a818-2b71f080a26f]
zealot-zealot | [75575112-72bd-4adb-a818-2b71f080a26f] app/controllers/application_controller.rb:30:in `set_sentry_context'
zealot-zealot | I, [2021-07-11T21:50:28.220736 #371]  INFO -- : [04acc99d-1864-4bd9-af15-8c8ae3be262d] Started GET "/health" for 127.0.0.1 at 2021-07-11 21:50:28 +0800
zealot-zealot | I, [2021-07-11T21:50:28.222166 #371]  INFO -- : [04acc99d-1864-4bd9-af15-8c8ae3be262d] Processing by HealthCheck::HealthCheckController#index as TEXT
zealot-zealot | I, [2021-07-11T21:50:28.231017 #371]  INFO -- : [04acc99d-1864-4bd9-af15-8c8ae3be262d]   Rendered text template (Duration: 0.0ms | Allocations: 2)
zealot-zealot | I, [2021-07-11T21:50:28.231336 #371]  INFO -- : [04acc99d-1864-4bd9-af15-8c8ae3be262d] health_check failed: [redis - ERR Client sent AUTH, but no password is set] ..
zealot-zealot | I, [2021-07-11T21:50:28.231622 #371]  INFO -- : [04acc99d-1864-4bd9-af15-8c8ae3be262d] Completed 500 Internal Server Error in 9ms (Views: 0.4ms | ActiveRecord: 0.8ms | Allocations: 1847)
```

镜像信息
```
REPOSITORY         TAG         IMAGE ID       CREATED         SIZE
tryzealot/zealot   nightly     a3fb211e32e6   6 hours ago     571MB
redis              5-alpine    51bbd55867dd   4 days ago      29.3MB
postgres           12-alpine   7d6f672908a4   2 weeks ago     190MB
icyleafcn/mkcert   latest      e7a54b344196   7 months ago    11.2MB
abiosoft/caddy     1.0.3       7b7636ac875d   23 months ago   53.3MB
```

看镜像的创建时间应该是 pull 成功了，但还是同样的错误

**Comment by icyleaf** [comment]
这次报的是 `set_extras` 是一个私有方法...我去查查手册之前好好的

**Comment by icyleaf** [comment]
麻烦再执行下 docker-compose pull 在运行看看

**Comment by mengx16** [comment]
已解决，可以正常打开了，登陆成功。感谢排查问题。
